stages:
- name: Build--NPM build dist
  steps:
  - runScriptConfig:
      image: 10.50.1.63:5443/iiidevops/node
      shellScript: pwd;ls;mv /iiidevops-ui/node_modules .;echo "VUE_APP_VERSION='${CICD_GIT_COMMIT}'" >> .env.staging; echo "VUE_APP_BASE_API = 'devops-system-develope-service:10009'" >> .env.staging;pwd;cat .env.staging; npm run build:stage
    env:
      PLUGIN_MTU: 1440

- name: Publish--vuejs image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: iiidevops/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 10.50.1.63:5443
    env:
      PLUGIN_MTU: 1440
      PLUGIN_INSECURE: true
- name: deploy--vuejs deployment and service on kubernetes
  steps:
  - applyYamlConfig:
      path: ./k8s-yaml/devopswebui-dev-deployment.yaml
  - applyYamlConfig:
      path: ./k8s-yaml/devopswebui-dev-service.yaml

